# Generated by Django 2.2.4 on 2019-11-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='nama')),
                ('kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.Jurusan')),
            ],
        ),
    ]
