# Generated by Django 2.2.4 on 2019-11-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.IntegerField()),
                ('jurusan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.Jurusan')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.Jurusan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.Kelas'),
        ),
    ]
