# Generated by Django 2.2.4 on 2019-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20191110_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='nama_jurusan',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
