# Generated by Django 2.2.4 on 2019-11-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20191110_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='jurusan',
        ),
    ]
